O campo txtDescricao informa o tipo de despesa. Quais são os valores presentes no DataFrame? Ordene de forma decrescente o vlrLiquido de cada partido para os gastos com txtDescricao igual a FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTA.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('reembolso-2019-completo.csv', dtype={'txtCNPJCPF': str, 'cnpj': str})

In [6]:
df.txtDescricao.unique()

array(['FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR',
       'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS.',
       'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.',
       'ASSINATURA DE PUBLICAÇÕES',
       'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR',
       'COMBUSTÍVEIS E LUBRIFICANTES.', 'PASSAGEM AÉREA - REEMBOLSO',
       'LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES',
       'HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO FEDERAL.',
       'PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS', 'TELEFONIA',
       'SERVIÇOS POSTAIS', 'PASSAGEM AÉREA - RPA',
       'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO',
       'PASSAGEM AÉREA - SIGEPA',
       'SERVIÇO DE SEGURANÇA PRESTADO POR EMPRESA ESPECIALIZADA.',
       'PARTICIPAÇÃO EM CURSO, PALESTRA OU EVENTO SIMILAR',
       'LOCAÇÃO OU FRETAMENTO DE AERONAVES',
       'LOCAÇÃO OU FRETAMENTO DE EMBARCAÇÕES'], dtype=object)

In [7]:
f = df.txtDescricao == 'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR'

In [10]:
df[f].groupby('sgPartido')['vlrLiquido'].sum().sort_values(ascending=False).to_frame()

               vlrLiquido
sgPartido
PT              235262.61
PSL             228952.81
PSD             132645.39
PP              112421.79
PSDB            104930.25
MDB              97737.77
PL               92781.22
REPUBLICANOS     71128.28
PDT              69299.26
DEM              63230.28
CIDADANIA        38118.15
PSB              35436.35
PTB              23697.43
PSC              18259.25
SOLIDARIEDADE    17824.70
PATRIOTA         16236.85
NOVO             14739.62
AVANTE           14168.62
PROS              7363.08
PCdoB             6583.06
PSOL              4132.02
PR                4128.73
PODE              3153.50
PRB               1779.36
PATRI             1253.42
PPS                901.29
PHS                299.20
PV                 143.02
REDE                62.62

In [14]:
df.groupby(['txtCNPJCPF', 'txtFornecedor'])['vlrLiquido'].sum().sort_values(ascending=False)[:10].to_frame()

                                                                    vlrLiquido
txtCNPJCPF     txtFornecedor
02012862000160 Cia Aérea - TAM                                     49410159.66
07575651000159 Cia Aérea - GOL                                     44015149.74
09296295000160 Cia Aérea - AZUL                                    12881217.22
07319323000191 PANTANAL VEÍCULOS LTDA                               4362549.04
02012862000160 TAM LINHAS AEREAS S/A.                               2344253.56
02575829000148 Cia Aérea - AVIANCA                                  2272357.30
23721017000133 T2 COMUNICACAO, VIDEO E PRODUCOES EIRELI - EPP       2194668.00
02558157000162 TELEFÔNICA BRASIL S.A. VIVO                          1721626.30
05443449000148 VERTICE - SOCIEDADE CIVIL DE PROFISSIONAIS ASSO...   1419734.00
07575651000159 GOL LINHAS AEREAS S.A.                               1236629.60